### ISSUE TITLE
Error al descargar la guia

### ISSUE THREAD

**Issue by Carlitos195** [MovistarTV/tv_grab_es_movistartv#10]
Tengo el script instalado en un synology, corriendo python2 y sin problemas de permisos.
el log que me sale es este cuando descargo el epg.

[22/09/2018 02:13:28] [INFO] ---------------------------------------------------
[22/09/2018 02:13:28] [INFO] MovistarTV EPG Grabber
[22/09/2018 02:13:28] [INFO] Parámetros: ['--output', '/volume1/kodi/guia.xml']
[22/09/2018 02:13:28] [INFO] ---------------------------------------------------
[22/09/2018 02:13:28] [INFO] Cookie: no encontrada
[22/09/2018 02:13:28] [INFO] tvPackages: ALL
[22/09/2018 02:13:28] [INFO] Demarcation: 19
[22/09/2018 02:13:28] [INFO] Buscando el Proveedor de Servicios de 19
[22/09/2018 02:13:28] [INFO] Proveedor de Servicios de 19: 239.0.2.154
[22/09/2018 02:13:28] [INFO] Canales: 424
[22/09/2018 02:13:28] [INFO] Paquetes: 166
[22/09/2018 02:13:28] [INFO] Días de EPG: 8
[22/09/2018 02:13:32] [INFO] Generando la guía XMLTV: descargando info extendida
[22/09/2018 02:13:32] [CRITICAL] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/bin/tv_grab_es_movistartv", line 1199, in <module>
    epg_x = xmltv.generate_xml(epg)
  File "/usr/bin/tv_grab_es_movistartv", line 926, in generate_xml
    root.append(self.__build_programme_tag(channel_id, parsed_epg[chid][program], tz))
  File "/usr/bin/tv_grab_es_movistartv", line 981, in __build_programme_tag
    keys = self.__get_key_and_subkey(program['genre'], config['genres'])
  File "/usr/bin/tv_grab_es_movistartv", line 938, in __get_key_and_subkey
    genre = next(genre for genre in genres if genre['id'].upper() == (code[0] if code[0] == '0' else ('%s%s' % (code[0], '0')).upper()))
TypeError: 'NoneType' object is not iterable

y no funciona ni crea nada :-(

**Comment by MovistarTV** [comment]
El error está arreglado, si no hay géneros no se generan las keywords. Vuelve a descargar el grabber y no te olvides de cambiar el propietario y los permisos.

Después de actualizar deberías poder descargar al menos la guía básica.

**Comment by MovistarTV** [comment]
:+1:
