### ISSUE TITLE
desde ayer me da una excepcion y no se genera la epg

### ISSUE THREAD

**Issue by cafs78** [MovistarTV/tv_grab_es_movistartv#11]
06/10/2018 18:47:30] [INFO] ---------------------------------------------------
[06/10/2018 18:47:30] [INFO] MovistarTV EPG Grabber
[06/10/2018 18:47:30] [INFO] Parámetros: ['--tvheadend', '/home/hts/MovistarTV']
[06/10/2018 18:47:30] [INFO] ---------------------------------------------------
[06/10/2018 18:47:30] [INFO] Cookie: JSESSIONID=474B6A811C821D8D07383AEC79E017A0-node9; Path=/appserver/; HttpOnly
[06/10/2018 18:47:30] [INFO] tvPackages: UTX6C|UTX6L
[06/10/2018 18:47:30] [INFO] Demarcation: 32
[06/10/2018 18:47:30] [INFO] Buscando el Proveedor de Servicios de Extremadura
[06/10/2018 18:47:30] [INFO] Proveedor de Servicios de Extremadura: 239.0.2.162
[06/10/2018 18:47:30] [INFO] Canales: 423
[06/10/2018 18:47:30] [INFO] Paquetes: 166
[06/10/2018 18:47:30] [INFO] Días de EPG: 8
[06/10/2018 18:47:30] [INFO] Multithread: 3 descargas simultáneas
[06/10/2018 18:47:30] [INFO] Descargando EPG_0_BIN.imagenio.es
[06/10/2018 18:47:30] [INFO] Descargando EPG_1_BIN.imagenio.es
[06/10/2018 18:47:30] [INFO] Descargando EPG_2_BIN.imagenio.es
[06/10/2018 18:48:08] [INFO] Descargando EPG_3_BIN.imagenio.es
[06/10/2018 18:48:09] [INFO] Descargando EPG_4_BIN.imagenio.es
[06/10/2018 18:48:09] [INFO] Descargando EPG_5_BIN.imagenio.es
[06/10/2018 18:48:12] [ERROR] Error al descargar los archivos XML: timed out
[06/10/2018 18:48:12] [INFO] Descargando EPG_6_BIN.imagenio.es
[06/10/2018 18:48:14] [INFO] Descargando EPG_7_BIN.imagenio.es
[06/10/2018 18:48:52] [CRITICAL] 'NoneType' object has no attribute 'keys'
Traceback (most recent call last):
  File "/home/pi/tv_grab_es_movistartv/tv_grab_es_movistartv.py", line 1199, in <module>
    epg = iptv.get_epg()
  File "/home/pi/tv_grab_es_movistartv/tv_grab_es_movistartv.py", line 779, in get_epg
    return self.__parse_bin_epg()
  File "/home/pi/tv_grab_es_movistartv/tv_grab_es_movistartv.py", line 885, in __parse_bin_epg
    for ch_id in epg_day.keys():
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by cafs78** [comment]
sin tener ni iea de como va el programa, poniendo un if en la funcion __parse_bin_epg parece que no peta justo en ese punto (solia petar muy al principio y ahora lleva ya un rato)

`
def __parse_bin_epg(self):
        merged_epg = {}
        for epg_day in self.__epg:
            if epg_day is not None:
                programs = {}
                for ch_id in epg_day.keys():
                    if epg_day[ch_id] and 'replacement' not in epg_day[ch_id]:
                        head = self.__parse_bin_epg_header(epg_day[ch_id])
                        programs[str(head['service_id'])] = self.__parse_bin_epg_body(head['data'])
                self.__merge_dicts(merged_epg, programs)
        logger.debug('Canales con EPG: %s' % len(merged_epg))
        cache.save_epg(merged_epg)
        return merged_epg
`

**Comment by MovistarTV** [comment]
No, no tiene sentido que `epg_day` sea `None`, precisamente por eso se genera la excepción y el programa se detiene. El valor es `None` porque falta un día de EPG. Durante la descarga uno de los hilos dio un timeout y no pudo obtener una parte de la guía.

La descarga de esta guía básica viene por Multicast y es multihilo, se conecta a varias IP simultáneamente para agilizar el tiempo de ejecución del grabber. Por defecto hay tres hilos (tres conexiones a tres IP diferentes) porque con cuatro o más algunos de los hilos empezaban a dar timeouts.

Parece ser que en tu caso tres hilos es demasiado... prueba a bajarlo a dos.

Edita el grabber y busca la línea:

`threads = 3`

Cámbiala por:

`threads = 2`

Si sigues teniendo problemas desactiva el multihilo. Busca la línea:

`use_multithread = True`

Y cámbiala por:

`use_multithread = False`

Si incluso con el multihilo desactivado sigue dando timeouts comprueba tu red.

**Comment by cafs78** [comment]
ok probaré, gracias

**Comment by Lordpedal** [comment]
Buenos días,

Desde ayer estoy recibiendo los siguientes errores:

```bash
pi@overclock:~/git/movistar$ ./tv_grab_es_movistartv.py --reset
pi@overclock:~/git/movistar$ ./tv_grab_es_movistartv.py --m3u Lordpedal.m3u
Excepción:

         dvbipiEntryPoint

Traceback:

        Traceback (most recent call last):
  File "./tv.py", line 1190, in <module>
    config = mtv.get_service_config()
  File "./tv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')
KeyError: 'dvbipiEntryPoint'

pi@overclock:~/git/movistar$ ./tv_grab_es_movistartv.py --output Lordpedal.xml
Excepción:

         dvbipiEntryPoint

Traceback:

        Traceback (most recent call last):
  File "./tv.py", line 1190, in <module>
    config = mtv.get_service_config()
  File "./tv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')
KeyError: 'dvbipiEntryPoint'
```
Y revisando el **log** muestra los siguientes errores:

```bash
pi@overclock:~/git/movistar/xmltv$ cat tv_grab_es_movistartv.log
[30/01/2021 12:06:43] [INFO] ---------------------------------------------------
[30/01/2021 12:06:43] [INFO] MovistarTV EPG Grabber
[30/01/2021 12:06:43] [INFO] Parámetros: ['--m3u', 'Lordpedal.m3u']
[30/01/2021 12:06:43] [INFO] ---------------------------------------------------
[30/01/2021 12:06:43] [INFO] Creando caché en /home/pi/git/movistar/xmltv/cache
[30/01/2021 12:06:43] [INFO] Cookie: no encontrada
[30/01/2021 12:06:43] [INFO] Descargando configuración del cliente
[30/01/2021 12:06:46] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:06:50] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:06:53] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:06:56] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:06:56] [ERROR] End Point http://www-60.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:06:59] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:07:02] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:07:05] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:07:08] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:07:08] [ERROR] End Point http://nc2.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:07:11] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:07:14] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:07:17] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:07:20] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:07:20] [ERROR] End Point http://nc4.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:07:23] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:07:26] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:07:29] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:07:33] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:07:33] [ERROR] End Point http://nc5.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:07:36] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:07:39] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:07:42] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:07:45] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:07:45] [ERROR] End Point http://nc6.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:07:45] [ERROR] Servicio Web de Movistar TV caído: decargando guía básica
[30/01/2021 12:07:45] [ERROR] Usando la configuración de cliente por defecto: 12|ALL|1
[30/01/2021 12:07:45] [INFO] Descargando pefil del servicio
[30/01/2021 12:07:45] [ERROR] Usando el pefil del servicio por defecto
[30/01/2021 12:07:45] [INFO] Descargando parámetros de configuración
[30/01/2021 12:07:45] [ERROR] Usando los parámetros de configuración por defecto
[30/01/2021 12:07:45] [CRITICAL] dvbipiEntryPoint
Traceback (most recent call last):
  File "./tv.py", line 1190, in <module>
    config = mtv.get_service_config()
  File "./tv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')
KeyError: 'dvbipiEntryPoint'

[30/01/2021 12:08:27] [INFO] ---------------------------------------------------
[30/01/2021 12:08:27] [INFO] MovistarTV EPG Grabber
[30/01/2021 12:08:27] [INFO] Parámetros: ['--output', 'Lordpedal.xml']
[30/01/2021 12:08:27] [INFO] ---------------------------------------------------
[30/01/2021 12:08:27] [INFO] Cookie: no encontrada
[30/01/2021 12:08:27] [INFO] Descargando configuración del cliente
[30/01/2021 12:08:30] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:08:33] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:08:36] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:08:40] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:08:40] [ERROR] End Point http://www-60.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:08:43] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:08:46] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:08:49] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:08:52] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:08:52] [ERROR] End Point http://nc2.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:08:55] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:08:58] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:09:01] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:09:04] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:09:04] [ERROR] End Point http://nc4.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:09:07] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:09:10] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:09:13] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:09:16] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:09:16] [ERROR] End Point http://nc5.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:09:19] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:09:23] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:09:26] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:09:29] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:09:29] [ERROR] End Point http://nc6.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:09:29] [ERROR] Servicio Web de Movistar TV caído: decargando guía básica
[30/01/2021 12:09:29] [ERROR] Usando la configuración de cliente por defecto: 12|ALL|1
[30/01/2021 12:09:29] [INFO] Descargando pefil del servicio
[30/01/2021 12:09:29] [ERROR] Usando el pefil del servicio por defecto
[30/01/2021 12:09:29] [INFO] Descargando parámetros de configuración
[30/01/2021 12:09:29] [ERROR] Usando los parámetros de configuración por defecto
[30/01/2021 12:09:29] [CRITICAL] dvbipiEntryPoint
Traceback (most recent call last):
  File "./tv.py", line 1190, in <module>
    config = mtv.get_service_config()
  File "./tv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')
KeyError: 'dvbipiEntryPoint'
```

En el script lo he probado tanto con `use_multithread = False` como `use_multithread = True` y con las **DNS** `80.58.61.254 80.58.61.250` , como `172.26.23.3`

Desconozco si es un fallo puntual de mi sistema o bien han cambiado las direcciones de obtención de EPG

Un saludo y gran trabajo
