### ISSUE TITLE
error repetitivo cada cierto tiempo

### ISSUE THREAD

**Issue by Yonoesio** [MovistarTV/tv_grab_es_movistartv#12]
Hola,

Cada cierto tiempo recibo el siguiente error:
`[23/10/2018 03:15:07] [CRITICAL] 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/usr/bin/tv_grab_es_movistartv", line 1204, in <module>
    xdata = iptv.get_service_provider_data()
  File "/usr/bin/tv_grab_es_movistartv", line 801, in get_service_provider_data
    self.__get_epg_data(connection['mcast_grp'], connection['mcast_port'])
  File "/usr/bin/tv_grab_es_movistartv", line 793, in __get_epg_data
    'channels': self.__get_channels(xml['2_0']),
TypeError: 'NoneType' object has no attribute '__getitem__'`

Solo se soluciona si reinicio el servidor. Después sigue funcionando sin problemas varios días hasta que vuelve a suceder y tengo que volver a reiniciar. Alguna idea de porque puede pasar?

Gracias.

**Comment by Yonoesio** [comment]
Arreglado... Era problema de IP del servidor. Cada vez que reinicio el router el servidor coge una IP fuera de rango. La he puesto como estática y ya no pasa.
