### ISSUE TITLE
CRITICAL Extra data: line 16961 column 1 - line 16961 column 2 (char 575295 - 575296)

### ISSUE THREAD

**Issue by Yonoesio** [MovistarTV/tv_grab_es_movistartv#14]
Hola de nuevo,
Nuevo error desde ayer.

` [CRITICAL] Extra data: line 16961 column 1 - line 16961 column 2 (char 575295 - 575296)
Traceback (most recent call last):
  File "/usr/bin/tv_grab_es_movistartv", line 1207, in <module>
    xdata = iptv.get_service_provider_data()
  File "/usr/bin/tv_grab_es_movistartv", line 804, in get_service_provider_data
    self.__get_epg_data(connection['mcast_grp'], connection['mcast_port'])
  File "/usr/bin/tv_grab_es_movistartv", line 786, in __get_epg_data
    data = cache.load_epg_data()
  File "/usr/bin/tv_grab_es_movistartv", line 394, in load_epg_data
    data = self.__load('epg_metadata.json')
  File "/usr/bin/tv_grab_es_movistartv", line 324, in __load
    content = json.load(fp)
  File "/usr/lib64/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 16961 column 1 - line 16961 column 2 (char 575295 - 575296)
`

**Comment by Yonoesio** [comment]
Se ha solucionado solo.
