### ISSUE TITLE
Excepción al parsear XML

### ISSUE THREAD

**Issue by actiobits2019** [MovistarTV/tv_grab_es_movistartv#19]
Antes de nada felicitar a todos los que han contribuido a este gran script.
Escribo para ver si alguien puede darme algo de luz porque no controlo nada de Python y ando un poco perdido. Al ejecutar el script para generar el M3U me devuelve el siguiente error:
> [23/04/2019 21:42:14] [INFO] Descargando configuración del cliente
[23/04/2019 21:42:20] [INFO] Set-Cookie: JSESSIONID=4B910E710AECE6DC1CB542BB41B388E2-node12; Path=/appserver/; HttpOnly
[23/04/2019 21:42:20] [INFO] Descargando pefil del servicio
[23/04/2019 21:42:20] [INFO] Descargando parámetros de configuración
[23/04/2019 21:42:20] [INFO] tvPackages: UTX6C|UTX6L
[23/04/2019 21:42:20] [INFO] Demarcation: 19
[23/04/2019 21:42:20] [INFO] Descargando mapa de géneros
[23/04/2019 21:42:20] [INFO] Buscando el Proveedor de Servicios de Madrid
[23/04/2019 21:45:32] [INFO] Canales: 413
[23/04/2019 21:45:32] [CRITICAL] mismatched tag: line 1, column 41650
Traceback (most recent call last):
  File "tv_grab_es_movistartv.py", line 1195, in <module>
    xdata = iptv.get_service_provider_data()
  File "tv_grab_es_movistartv.py", line 804, in get_service_provider_data
    self.__get_epg_data(connection['mcast_grp'], connection['mcast_port'])
  File "tv_grab_es_movistartv.py", line 797, in __get_epg_data
    'packages': self.__get_packages(xml['5_0']),
  File "tv_grab_es_movistartv.py", line 667, in __get_packages
    root = ElTr.fromstring(xml.replace('\n', ' '))
  File "<string>", line 124, in XML
ParseError: mismatched tag: line 1, column 41650

¿Alguien sabe por donde pueden ir los tiros?

Muchas gracias.

**Comment by actiobits2019** [comment]
También en ocasiones devuelve este otro:
> Traceback:

        Traceback (most recent call last):
  File "tv_grab_es_movistartv.py", line 1199, in <module>
    xdata = iptv.get_service_provider_data()
  File "tv_grab_es_movistartv.py", line 808, in get_service_provider_data
    self.__get_epg_data(connection['mcast_grp'], connection['mcast_port'])
  File "tv_grab_es_movistartv.py", line 800, in __get_epg_data
    'channels': self.__get_channels(xml['2_0']),
  File "tv_grab_es_movistartv.py", line 644, in __get_channels
    root = ElTr.fromstring(xml_channels.replace('\n', ' '))
  File "<string>", line 124, in XML
ParseError: not well-formed (invalid token): line 1, column 158147

**Comment by MovistarTV** [comment]
Han hecho cambios y aún no sé si el error está relacionado con ellos o no...

**Comment by actiobits2019** [comment]
He guardado el XML en un archivo y viene como cortado, faltan etiquetas... no se, voy a probar conectado por cable (solo lo he hecho vía wifi) y a ver qué sale.
Muchas gracias!

**Comment by MovistarTV** [comment]
Sí, está descargando mal los archivos XML, per ono he podido reproducir el fallo.

¿Por cable todo bien?

**Comment by actiobits2019** [comment]
Buenas noches. 
Pueees ahora resulta que me devuelve un error distinto
>[08/05/2019 21:58:46] [INFO] ---------------------------------------------------
[08/05/2019 21:58:46] [INFO] MovistarTV EPG Grabber
[08/05/2019 21:58:46] [INFO] Parámetros: ['--output', '/home/sergio/movistar/guia.xml']
[08/05/2019 21:58:46] [INFO] ---------------------------------------------------
[08/05/2019 21:58:46] [INFO] Creando caché en /home/sergio/movistar/cache
[08/05/2019 21:58:46] [INFO] Cookie: no encontrada
[08/05/2019 21:58:46] [INFO] Descargando configuración del cliente
[08/05/2019 21:58:46] [INFO] Set-Cookie: JSESSIONID=C93702D830C51C6C83900CF8CE42D947-node8; Path=/appserver/; HttpOnly
[08/05/2019 21:58:46] [INFO] Descargando pefil del servicio
[08/05/2019 21:58:46] [INFO] Descargando parámetros de configuración
[08/05/2019 21:58:46] [CRITICAL] dvbEntryPoint
Traceback (most recent call last):
  File "tv_grab_es_movistartv.py", line 1191, in <module>
    config = mtv.get_service_config()
  File "tv_grab_es_movistartv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbEntryPoint'].split(':')
KeyError: 'dvbEntryPoint'

**Comment by MovistarTV** [comment]
Han hecho más cambios (Issue #21)

**Comment by actiobits2019** [comment]
He encontrado que platform['dvbConfig'] contiene las claves dvbServiceProvider y dvbipiEntryPoint, parece que la clave dvbEntryPoint ya no existe...
Lo he modificado y por cable parece que va.
