### ISSUE TITLE
Error al generar la epg

### ISSUE THREAD

**Issue by Spufy** [MovistarTV/tv_grab_es_movistartv#21]
Desde esta mañana me está dando este error al obtener la EPG. No se si a alguien le está pasando lo mismo:

xmltv: /usr/bin/tv_grab_es_movistartv: grab /usr/bin/tv_grab_es_movistartv
Executing "/usr/bin/tv_grab_es_movistartv"
Traceback (most recent call last):
File "/usr/bin/tv_grab_es_movistartv", line 1230, in <module>
print u'Excepción:\n\n\t %s\n\nTraceback:\n\n\t%s' % (e.message, traceback.format_exc())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 7: ordinal not in range(128)
/usr/bin/tv_grab_es_movistartv: no output detected
/usr/bin/tv_grab_es_movistartv: grab returned no data

**Comment by actiobits2019** [comment]
> Han hecho más cambios, estoy en ello.

Vaya trabajazo te damos...si se puede ayudar en algo, aquí unas manos.

**Comment by actiobits2019** [comment]
Usando _dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')_ y por cable, todo ok
>[08/05/2019 22:13:19] [INFO] ---------------------------------------------------
[08/05/2019 22:13:19] [INFO] MovistarTV EPG Grabber
[08/05/2019 22:13:19] [INFO] Parámetros: ['--output', '/home/sergio/movistar/guia.xml']
[08/05/2019 22:13:19] [INFO] ---------------------------------------------------
[08/05/2019 22:13:19] [INFO] Cookie: JSESSIONID=C93702D830C51C6C83900CF8CE42D947-node8; Path=/appserver/; HttpOnly
[08/05/2019 22:13:19] [INFO] Descargando configuración del cliente
[08/05/2019 22:13:19] [INFO] Descargando pefil del servicio
[08/05/2019 22:13:19] [INFO] Descargando parámetros de configuración
[08/05/2019 22:13:49] [INFO] tvPackages: UTX6C|UTX6L
[08/05/2019 22:13:49] [INFO] Demarcation: 19
[08/05/2019 22:13:49] [INFO] Nuevos End Points: [u'epNoCach4', u'epNoCach5', u'epNoCach6', u'epNoCach1', u'epNoCach2', u'epNoCach3']
[08/05/2019 22:13:49] [INFO] Descargando mapa de géneros
[08/05/2019 22:13:49] [INFO] Buscando el Proveedor de Servicios de Madrid
[08/05/2019 22:13:52] [INFO] Proveedor de Servicios de Madrid: 239.0.2.154
[08/05/2019 22:13:52] [INFO] Descargando canales, paquetes e índices
[08/05/2019 22:16:09] [INFO] Canales: 405
[08/05/2019 22:16:09] [INFO] Paquetes: 311
[08/05/2019 22:16:09] [INFO] Días de EPG: 8
[08/05/2019 22:16:16] [INFO] Multithread: 3 descargas simultáneas
[08/05/2019 22:16:16] [INFO] Descargando EPG_0_BIN.imagenio.es
[08/05/2019 22:16:16] [INFO] Descargando EPG_1_BIN.imagenio.es
[08/05/2019 22:16:16] [INFO] Descargando EPG_2_BIN.imagenio.es
[08/05/2019 22:17:39] [INFO] Descargando EPG_3_BIN.imagenio.es
[08/05/2019 22:17:39] [INFO] Descargando EPG_4_BIN.imagenio.es
[08/05/2019 22:17:40] [INFO] Descargando EPG_5_BIN.imagenio.es
[08/05/2019 22:18:59] [INFO] Descargando EPG_6_BIN.imagenio.es
[08/05/2019 22:19:00] [INFO] Descargando EPG_7_BIN.imagenio.es
[08/05/2019 22:24:52] [INFO] Generando la guía XMLTV: descargando info extendida
[08/05/2019 22:38:39] [INFO] Guardando la guía XMLTV: /home/sergio/movistar/guia.xml
[08/05/2019 22:39:06] [INFO] EPG de 200 canales y 8 días descargada en 25 minutos
[08/05/2019 22:40:37] [INFO] ---------------------------------------------------
[08/05/2019 22:40:37] [INFO] MovistarTV EPG Grabber
[08/05/2019 22:40:37] [INFO] Parámetros: ['--m3u', '/home/sergio/movistar/MovistarTV.m3u']
[08/05/2019 22:40:37] [INFO] ---------------------------------------------------
[08/05/2019 22:40:37] [INFO] Cookie: JSESSIONID=C93702D830C51C6C83900CF8CE42D947-node8; Path=/appserver/; HttpOnly
[08/05/2019 22:40:37] [INFO] tvPackages: UTX6C|UTX6L
[08/05/2019 22:40:37] [INFO] Demarcation: 19
[08/05/2019 22:40:37] [INFO] Buscando el Proveedor de Servicios de Madrid
[08/05/2019 22:40:37] [INFO] Proveedor de Servicios de Madrid: 239.0.2.154
[08/05/2019 22:40:37] [INFO] Canales: 405
[08/05/2019 22:40:37] [INFO] Paquetes: 311
[08/05/2019 22:40:37] [INFO] Días de EPG: 8
[08/05/2019 22:40:37] [INFO] Lista de canales exportada: /home/sergio/movistar/MovistarTV.m3u

**Comment by actiobits2019** [comment]
Por wifi nada, casca aquí
>[08/05/2019 22:46:01] [INFO] ---------------------------------------------------
[08/05/2019 22:46:01] [INFO] MovistarTV EPG Grabber
[08/05/2019 22:46:01] [INFO] Parámetros: ['--output', '/home/sergio/movistar/guia.xml']
[08/05/2019 22:46:01] [INFO] ---------------------------------------------------
[08/05/2019 22:46:01] [INFO] Creando caché en /home/sergio/movistar/cache
[08/05/2019 22:46:01] [INFO] Cookie: no encontrada
[08/05/2019 22:46:01] [INFO] Descargando configuración del cliente
[08/05/2019 22:46:02] [INFO] Set-Cookie: JSESSIONID=E3569921660C80D4181496A9266547FD-node3; Path=/appserver/; HttpOnly
[08/05/2019 22:46:02] [INFO] Descargando pefil del servicio
[08/05/2019 22:46:02] [INFO] Descargando parámetros de configuración
[08/05/2019 22:46:02] [INFO] tvPackages: UTX6C|UTX6L
[08/05/2019 22:46:02] [INFO] Demarcation: 19
[08/05/2019 22:46:02] [INFO] Nuevos End Points: [u'epNoCach4', u'epNoCach5', u'epNoCach6', u'epNoCach1', u'epNoCach2', u'epNoCach3']
[08/05/2019 22:46:02] [INFO] Descargando mapa de géneros
[08/05/2019 22:46:02] [INFO] Buscando el Proveedor de Servicios de Madrid
[08/05/2019 22:46:04] [INFO] Proveedor de Servicios de Madrid: 239.0.2.154
[08/05/2019 22:46:04] [INFO] Descargando canales, paquetes e índices
[08/05/2019 22:48:58] [INFO] Canales: 405
[08/05/2019 22:48:58] [CRITICAL] mismatched tag: line 1, column 267970
Traceback (most recent call last):
  File "tv_grab_es_movistartv.py", line 1196, in <module>
    xdata = iptv.get_service_provider_data()
  File "tv_grab_es_movistartv.py", line 805, in get_service_provider_data
    self.__get_epg_data(connection['mcast_grp'], connection['mcast_port'])
  File "tv_grab_es_movistartv.py", line 798, in __get_epg_data
    'packages': self.__get_packages(xml['5_0']),
  File "tv_grab_es_movistartv.py", line 668, in __get_packages
    root = ElTr.fromstring(xml.replace('\n', ' '))
  File "<string>", line 124, in XML
ParseError: mismatched tag: line 1, column 267970

**Comment by MovistarTV** [comment]
> Usando dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':') y por cable, todo ok

Sí, eso parece. Yo estoy en pruebas todavía. En cuanto confirme que todo está bien subo el cambio.

> Vaya trabajazo te damos...si se puede ayudar en algo, aquí unas manos.

Por mí encantado

**Comment by actiobits2019** [comment]
> El XML está corrupto o incompleto ¿Hay buena señal?
A 1 metro del router...eso si, es la castaña que monta Movistar y con un Asus de 14 años 
> Por mí encantado
Pues a debuguear se ha dicho. No tengo demasiado tiempo, pero ayudaré en lo que pueda

**Comment by MovistarTV** [comment]
El problema seguramente sea el ASUS de 14 años... puede que no se lleve muy bien con el tráfico multicast.

**Comment by MovistarTV** [comment]
Arreglado.

**Comment by Spufy** [comment]
Probado y funcionando perfectamente. Muchas gracias por la rápidez.
Gracias
