### ISSUE TITLE
Error al ejecutar script

### ISSUE THREAD

**Issue by tiempososcuros** [MovistarTV/tv_grab_es_movistartv#29]
He clonado el repositorio, y modificado los siguientes parámetros:
```
default_demarcation = demarcations['Islas Canarias']

app_dir = '/etc/tvheadend/hts/.xmltv'
```
El app_dir tiene los permisos adecuados:
```
[root@vision ~]# ls -ld /etc/tvheadend/
drwxr-x--- 3 tvheadend video 17 Dec  8 13:39 /etc/tvheadend/
[root@vision ~]# ls -ld /etc/tvheadend/hts/
drwxr-x--- 3 tvheadend video 20 Dec  8 15:37 /etc/tvheadend/hts/
```
Al ejecutar el script muestra error.

```
[root@vision tv_grab_es_movistartv]# ./tv_grab_es_movistartv.py
Excepción:

         'NoneType' object has no attribute '__getitem__'

Traceback:

        Traceback (most recent call last):
  File "./tv_grab_es_movistartv.py", line 1195, in <module>
    xdata = iptv.get_service_provider_data()
  File "./tv_grab_es_movistartv.py", line 804, in get_service_provider_data
    self.__get_epg_data(connection['mcast_grp'], connection['mcast_port'])
  File "./tv_grab_es_movistartv.py", line 796, in __get_epg_data
    'channels': self.__get_channels(xml['2_0']),
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by tiempososcuros** [comment]
Era el firewall.
Lo desactivé y ahora funciona.
