### ISSUE TITLE
Error al ejecutar generar lista canales. Excepción:  'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by miguelillo84** [MovistarTV/tv_grab_es_movistartv#30]
Buenas, 

Estoy tratando de generar la lista de canales. Sin embargo, la ejecución del script me devuelve el siguiente error:

`pi@raspberrypi:/home/hts $ sudo tv_grab_es_movistartv --m3u /home/pi/
Excepción:
         'NoneType' object has no attribute '__getitem__'
Traceback:
        Traceback (most recent call last):
  File "/usr/bin/tv_grab_es_movistartv", line 1195, in <module>
    xdata = iptv.get_service_provider_data()
  File "/usr/bin/tv_grab_es_movistartv", line 804, in get_service_provider_data
    self.__get_epg_data(connection['mcast_grp'], connection['mcast_port'])
  File "/usr/bin/tv_grab_es_movistartv", line 796, in __get_epg_data
    'channels': self.__get_channels(xml['2_0']),
TypeError: 'NoneType' object has no attribute '__getitem__'
`

Un saludo

**Comment by MovistarTV** [comment]
Tiene toda la pinta de ser un problema de DNS.

Desde la RPi haz un:
```
nslookup www-60.svc.imagenio.telefonica.net
```
Debebía devolverte algo así:
```
Non-authoritative answer:
Name:	www-60.svc.imagenio.telefonica.net
Address: 172.26.22.23
```

**Comment by Lordpedal** [comment]
Buenas,

En la última semana me esta devolviendo el siguiente error en la generación de la guía:

```bash
pi@debian9kvm:~/movistartv/xmltv$ cat tv_grab_es_movistartv.log
[28/12/2020 06:37:15] [INFO] ---------------------------------------------------
[28/12/2020 06:37:15] [INFO] MovistarTV EPG Grabber
[28/12/2020 06:37:15] [INFO] Parámetros: ['--help']
[28/12/2020 06:37:15] [INFO] ---------------------------------------------------
[28/12/2020 06:37:25] [INFO] ---------------------------------------------------
[28/12/2020 06:37:25] [INFO] MovistarTV EPG Grabber
[28/12/2020 06:37:25] [INFO] Parámetros: ['--m3u', '1.m3u']
[28/12/2020 06:37:25] [INFO] ---------------------------------------------------
[28/12/2020 06:37:25] [INFO] Creando caché en /home/pi/movistartv/xmltv/cache
[28/12/2020 06:37:25] [INFO] Cookie: no encontrada
[28/12/2020 06:37:25] [INFO] Descargando configuración del cliente
[28/12/2020 06:37:25] [INFO] Set-Cookie: JSESSIONID=3EBE0E7F325E40C4648BC260C314CF70-node8; Path=/appserver; HttpOnly
[28/12/2020 06:37:25] [INFO] Descargando pefil del servicio
[28/12/2020 06:37:25] [INFO] Descargando parámetros de configuración
[28/12/2020 06:37:25] [INFO] tvPackages: UTXCP|UTXF1
[28/12/2020 06:37:25] [INFO] Demarcation: 12
[28/12/2020 06:37:25] [INFO] Nuevos End Points: [u'epNoCach8', u'epNoCach9', u'epNoCach4', u'epNoCach5', u'epNoCach6', u'epNoCach7', u'epNoCach1', u'epNoCach2', u'epNoCach3', u'epNoCach10', u'epNoCach11']
[28/12/2020 06:37:25] [INFO] Descargando mapa de géneros
[28/12/2020 06:37:25] [INFO] Buscando el Proveedor de Servicios de Murcia
[28/12/2020 06:37:27] [INFO] Proveedor de Servicios de Murcia: 239.0.2.148
[28/12/2020 06:37:27] [INFO] Descargando canales, paquetes e índices
[28/12/2020 06:38:15] [INFO] Canales: 443
[28/12/2020 06:38:15] [INFO] Paquetes: 397
[28/12/2020 06:38:15] [INFO] Días de EPG: 8
[28/12/2020 06:38:15] [INFO] Lista de canales exportada: 1.m3u
[28/12/2020 06:39:45] [INFO] ---------------------------------------------------
[28/12/2020 06:39:45] [INFO] MovistarTV EPG Grabber
[28/12/2020 06:39:45] [INFO] Parámetros: ['--output', '/home/pi/git/rss/guia.xml']
[28/12/2020 06:39:45] [INFO] ---------------------------------------------------
[28/12/2020 06:39:45] [INFO] Cookie: JSESSIONID=3EBE0E7F325E40C4648BC260C314CF70-node8; Path=/appserver; HttpOnly
[28/12/2020 06:39:45] [INFO] tvPackages: UTXCP|UTXF1
[28/12/2020 06:39:45] [INFO] Demarcation: 12
[28/12/2020 06:39:45] [INFO] Buscando el Proveedor de Servicios de Murcia
[28/12/2020 06:39:45] [INFO] Proveedor de Servicios de Murcia: 239.0.2.148
[28/12/2020 06:39:45] [INFO] Canales: 443
[28/12/2020 06:39:45] [INFO] Paquetes: 397
[28/12/2020 06:39:45] [INFO] Días de EPG: 8
[28/12/2020 06:39:45] [INFO] Multithread: 3 descargas simultáneas
[28/12/2020 06:39:45] [INFO] Descargando EPG_0_BIN.imagenio.es
[28/12/2020 06:39:45] [INFO] Descargando EPG_1_BIN.imagenio.es
[28/12/2020 06:39:45] [INFO] Descargando EPG_2_BIN.imagenio.es
[28/12/2020 06:39:48] [ERROR] Error al descargar los archivos XML: ('timed out',)
[28/12/2020 06:39:48] [INFO] Descargando EPG_3_BIN.imagenio.es
[28/12/2020 06:39:48] [ERROR] Error al descargar los archivos XML: ('timed out',)
[28/12/2020 06:39:48] [INFO] Descargando EPG_4_BIN.imagenio.es
[28/12/2020 06:41:09] [INFO] Descargando EPG_5_BIN.imagenio.es
[28/12/2020 06:41:11] [INFO] Descargando EPG_6_BIN.imagenio.es
[28/12/2020 06:41:13] [INFO] Descargando EPG_7_BIN.imagenio.es
[28/12/2020 06:43:14] [CRITICAL] 'NoneType' object has no attribute 'keys'
Traceback (most recent call last):
  File "/usr/local/bin/tv_grab_es_movistartv", line 1204, in <module>
    epg = iptv.get_epg()
  File "/usr/local/bin/tv_grab_es_movistartv", line 783, in get_epg
    return self.__parse_bin_epg()
  File "/usr/local/bin/tv_grab_es_movistartv", line 889, in __parse_bin_epg
    for ch_id in epg_day.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
```

La lista de canales la genera correctamente pero la guía falla, probando el comando que comentas:
