### ISSUE TITLE
Error al descargar los XML: dirección solicitada no válida en este contexto

### ISSUE THREAD

**Issue by Charlio99** [MovistarTV/tv_grab_es_movistartv#32]
Al intentar descargar los XML salta este error. Estoy usando los DNS que tocan y me resuelven todos los dominios.

`[06/05/2020 23:39:55] [INFO] Cookie: JSESSIONID=01FC577CFF0783D7E1EEA42FBA90C2B3-node8; Path=/appserver; HttpOnly
[06/05/2020 23:39:55] [INFO] tvPackages: UTX6C|UTX6J
[06/05/2020 23:39:55] [INFO] Demarcation: 10
[06/05/2020 23:39:55] [INFO] Buscando el Proveedor de Servicios de Islas Baleares
[06/05/2020 23:39:55] [ERROR] Error al descargar los archivos XML: (10049, 'La direcci\xf3n solicitada no es v\xe1lida en este contexto')
[06/05/2020 23:39:55] [ERROR] Usando el Proveedor de Servicios por defecto: 239.0.2.150
[06/05/2020 23:39:55] [INFO] Descargando canales, paquetes e índices
[06/05/2020 23:39:55] [ERROR] Error al descargar los archivos XML: (10049, 'La direcci\xf3n solicitada no es v\xe1lida en este contexto')
[06/05/2020 23:39:55] [CRITICAL] 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "C:/Users/Carlitos/OneDrive - La Salle/Carlos/tv_movistar/app.py", line 1292, in <module>
    xdata = iptv.get_service_provider_data()
  File "C:/Users/Carlitos/OneDrive - La Salle/Carlos/tv_movistar/app.py", line 794, in get_service_provider_data
    self.__get_epg_data(connection['mcast_grp'], connection['mcast_port'])
  File "C:/Users/Carlitos/OneDrive - La Salle/Carlos/tv_movistar/app.py", line 786, in __get_epg_data
    'channels': self.__get_channels(xml['2_0']),
TypeError: 'NoneType' object has no attribute '__getitem__'`

**Comment by MovistarTV** [comment]
¿De verdad estás intentando ejecutarlo desde Windows?

No lo puse en el README porque es obvio: es un grabber pensado para TVHeadend, por lo tanto sólo hay soporte para sistemas GNU/Linux.

**Comment by Charlio99** [comment]
No, lo he ejecutado con el IDE para poder intentar sacar el error con el debugger y no tener que ponerme a instalar nada en el contenedor de Docker donde lo había montado.
Tengo exactamente el mismo error en Debian, Ubuntu, contenedor de Docker con Alpine y con el contendor de docker de Python3.

**Comment by MovistarTV** [comment]
Pon un punto de interrupción en la línea 608 y mira a ver qué valores tienen `mc_grp` y `mc_port`

(también vale poner `log_level = logging.DEBUG`)

**Comment by Charlio99** [comment]
> Pon un punto de interrupción en la línea 608 y mira a ver qué valores tienen `mc_grp` y `mc_port`
> 
> (también vale poner `log_level = logging.DEBUG` para que aparezca en el log)

![image](https://user-images.githubusercontent.com/7070420/81485048-bc250780-924a-11ea-930f-a5bd109f071b.png)

**Comment by MovistarTV** [comment]
Avanza en el depurador para ver qué línea exacta está dando la excepción...

**Comment by Charlio99** [comment]
> Avanza en el depurador para ver qué línea exacta está dando la excepción...

Tienes el traceback en mi primer comentario. Línea 796, está intentando acceder a un array vacío

**Comment by MovistarTV** [comment]
No, no... el error es éste:
```
[ERROR] Error al descargar los archivos XML: (10049, 'La direcci\xf3n solicitada no es v\xe1lida en este contexto')
```
Se está produciendo una excepción en el método `__get_xml_files()` y para saber qué pasa necesito saber qué línea la está generando...

**Comment by Charlio99** [comment]
> No, no... el error es éste:
> 
> ```
> [ERROR] Error al descargar los archivos XML: (10049, 'La direcci\xf3n solicitada no es v\xe1lida en este contexto')
> ```
> 
> Se está produciendo una excepción en el método `__get_xml_files()` y para saber qué pasa necesito saber qué línea la está generando...

Ah vale vale, ya te entiendo. Línea 612 `sock.bind((mc_grp, int(mc_port)))`

**Comment by MovistarTV** [comment]
Pon la tabla de rutas del router, me da que la cosa va a ir por ahí...

**Comment by Charlio99** [comment]
> Pon la tabla de rutas del router, me da que la cosa va a ir por ahí...

Cual necesitas, el RIP de la vlan de la IPTV?

**Comment by MovistarTV** [comment]
La tabla completa y así vemos si te estan llegando todas las rutas

**Comment by Charlio99** [comment]
> La tabla completa y así vemos si te estan llegando todas las rutas

Bueno, te paso la tabla entera de la vlan de la IPTV, la tabla completa por aquí no la paso que tiene IPs públicas de túneles que tengo hechos y no es como para ir publicándolo aquí para que cualquiera lo vea.

![image](https://user-images.githubusercontent.com/7070420/81485525-fa6ff600-924d-11ea-917c-d447f864859f.png)

**Comment by MovistarTV** [comment]
Vale, vale... no te peocupes, es suficiente.

Además el tráfico es Multicast, ésto en todo caso estaría relacionado con `igmpproxy` o lo que utilices para el reenvío de paquetes IGMP.

Cambia:
```sh
sock.bind((mc_grp, int(mc_port)))
```
Por:
```sh
sock.bind(('', int(mc_port)))
```
Y prueba a ver...

**Comment by Charlio99** [comment]
Te dejo el log 
```
[09/05/2020 23:59:35] [DEBUG] Cache: config.json guardado
[09/05/2020 23:59:39] [INFO] Buscando el Proveedor de Servicios de Islas Baleares
[09/05/2020 23:59:39] [DEBUG] Caché: datos del Proveedor de Servicios no encontrados
[09/05/2020 23:59:39] [DEBUG] Descargando XML de 239.0.2.129:3937
[10/05/2020 00:00:25] [DEBUG] XML: 1_0
[10/05/2020 00:00:54] [DEBUG] Cache: provider.json guardado
[10/05/2020 00:00:54] [INFO] Proveedor de Servicios de Islas Baleares: 239.0.2.146
[10/05/2020 00:00:56] [DEBUG] Caché: metadatos de la EPG no encontrados
[10/05/2020 00:00:56] [INFO] Descargando canales, paquetes e índices
[10/05/2020 00:00:56] [DEBUG] Descargando XML de 239.0.2.146:3937
[10/05/2020 00:02:14] [DEBUG] XML: 2_0
[10/05/2020 00:02:26] [DEBUG] XML: 6_0
[10/05/2020 00:04:05] [DEBUG] XML: 5_0
[10/05/2020 00:04:30] [DEBUG] El canal 4803 no tiene la estructura correcta: ('child index out of range',)
[10/05/2020 00:04:30] [DEBUG] El canal 4717 no tiene la estructura correcta: ('child index out of range',)
[10/05/2020 00:04:30] [DEBUG] El canal 4804 no tiene la estructura correcta: ('child index out of range',)
[10/05/2020 00:04:30] [INFO] Canales: 417
[10/05/2020 00:04:30] [INFO] Paquetes: 382
[10/05/2020 00:04:30] [INFO] Días de EPG: 8
```

Ha generado un archivo epg_metadata.json con un motón de cosas dentro que parece ser un mapeo de canales.

Todo correcto ahora, no?

**Comment by MovistarTV** [comment]
Sí, ya lo tienes...

**Comment by MovistarTV** [comment]
¿Te importa probalo en Windows? No voy a dar soporte, pero por saber si va...

**Comment by Charlio99** [comment]
> ¿Te importa probalo en Windows? No voy a dar soporte, pero por saber si va...

Todo lo que estoy haciendo lo hago desde un IDE en Windows. Instalar python2.7 y listo, no he instalado mucho más en el venv. Lo único que hay que ir con ojo con las rutas que se le pone, que windows es muy especialito (C:/ en vez de C:\ por ejemplo). El m3u lo genera con 0 problemas!

Muchísimas gracias!

**Comment by MovistarTV** [comment]
A tí...

Lo voy a dejar abierto por si a alguien le surge el mismo problema o le da por motarlo en Windows.
