### ISSUE TITLE
Cambio a la versión 2 de la EPG extendida

### ISSUE THREAD

**Issue by MovistarTV** [MovistarTV/tv_grab_es_movistartv#33]
Aprovechando los últimos cambios que ha hecho Movistar, he cambiado a la versión 2 de la API de la EPG extendida, la misma que usan los decos UHD/4K.

En la nueva API el campo `synopsis` es una descripción corta limitada a un máximo de caracteres. La descripción completa ahora está en `description` y éste cambio crea problemas con la caché.

Antes de actualizar el script hay resetarla:
```sh
tv_grab_es_movistartv --reset
```
Si os surge algún problema relacionado con el cambio de versión de la API podéis comentarlo aquí.

**Comment by magiaoscar** [comment]
Muchas gracias por la actualización, llevo unos meses usando el script y es genial

**Comment by Lordpedal** [comment]
Buenos días,

Desde anoche estoy viendo arrastrado este fallo que adjunto:

**Comment by Lordpedal** [comment]
Buenas tardes,

Desde hace unos días estoy viendo arrastrado este fallo que adjunto, desconozco si es un caso aislado o general.
El error lo obtengo tanto al generar lista como la guía.

Adjunto datos de petición:

```bash
rm -rf /home/pi/git/movistar/xmltv/cache && python2 tv.py --reset && python2 tv.py --m3u MovistarTV.m3u && \
rm -rf /home/pi/git/movistar/xmltv/cache && python2 tv.py --reset && python2 tv.py --output guia.xml
```

Y el error del log que arroja es el siguiente:

```bash
[13/06/2022 20:33:34] [INFO] ---------------------------------------------------
[13/06/2022 20:33:34] [INFO] MovistarTV EPG Grabber
[13/06/2022 20:33:34] [INFO] Parámetros: ['--m3u', '/home/pi/git/rss/MovistarTV.m3u']
[13/06/2022 20:33:34] [INFO] ---------------------------------------------------
[13/06/2022 20:33:34] [INFO] Creando caché en /home/pi/git/movistar/xmltv/cache
[13/06/2022 20:33:34] [INFO] Cookie: no encontrada
[13/06/2022 20:33:34] [DEBUG] Caché: configuración no encontrada
[13/06/2022 20:33:34] [INFO] Descargando configuración del cliente
[13/06/2022 20:33:34] [DEBUG] End Points: buscando
[13/06/2022 20:33:34] [DEBUG] End Points: por defecto
[13/06/2022 20:33:35] [INFO] Set-Cookie: JSESSIONID=XXXXXXXXXXXXXXXXXXXXXXXXXXXX-node3; Path=/appserver; HttpOnly
[13/06/2022 20:33:35] [DEBUG] Cache: tv_grab_es_movistartv.cookie guardado
[13/06/2022 20:33:35] [INFO] Descargando pefil del servicio
[13/06/2022 20:33:35] [DEBUG] End Points: buscando
[13/06/2022 20:33:35] [DEBUG] End Points: por defecto
[13/06/2022 20:33:35] [INFO] Descargando parámetros de configuración
[13/06/2022 20:33:35] [DEBUG] End Points: buscando
[13/06/2022 20:33:35] [DEBUG] End Points: por defecto
[13/06/2022 20:33:35] [INFO] tvPackages: UTXIG|UTXII|UTXIJ
[13/06/2022 20:33:35] [INFO] Demarcation: 12
[13/06/2022 20:33:35] [DEBUG] End Points: buscando
[13/06/2022 20:33:35] [DEBUG] End Points: por defecto
[13/06/2022 20:33:35] [INFO] Nuevos End Points: [u'epNoCach8', u'epNoCach9', u'epNoCach4', u'epNoCach5', u'epNoCach6', u'epNoCach7', u'epNoCach1', u'epNoCach2', u'epNoCach3', u'epNoCach10', u'epNoCach11']
[13/06/2022 20:33:35] [DEBUG] Cache: tv_grab_es_movistartv.endpoints guardado
[13/06/2022 20:33:35] [CRITICAL] RES_BASE_URI
Traceback (most recent call last):
  File "tv.py", line 1191, in <module>
    config = mtv.get_service_config()
  File "tv.py", line 532, in get_service_config
    'tvChannelLogoPath': '%s%s' % (platform['RES_BASE_URI'], params['tvChannelLogoPath']),
KeyError: 'RES_BASE_URI'

[13/06/2022 20:33:35] [INFO] ---------------------------------------------------
[13/06/2022 20:33:35] [INFO] MovistarTV EPG Grabber
[13/06/2022 20:33:35] [INFO] Parámetros: ['--output', '/home/pi/git/rss/guia.xml']
[13/06/2022 20:33:35] [INFO] ---------------------------------------------------
[13/06/2022 20:33:35] [DEBUG] Caché: tv_grab_es_movistartv.cookie cargado
[13/06/2022 20:33:35] [INFO] Cookie: JSESSIONID=XXXXXXXXXXXXXXXXXXXXXXXXXXXX-node3; Path=/appserver; HttpOnly
[13/06/2022 20:33:35] [DEBUG] Caché: configuración no encontrada
[13/06/2022 20:33:35] [INFO] Descargando configuración del cliente
[13/06/2022 20:33:35] [DEBUG] End Points: buscando
[13/06/2022 20:33:35] [DEBUG] Caché: tv_grab_es_movistartv.endpoints cargado
[13/06/2022 20:33:35] [INFO] Descargando pefil del servicio
[13/06/2022 20:33:35] [INFO] Descargando parámetros de configuración
[13/06/2022 20:33:35] [INFO] tvPackages: UTXIG|UTXII|UTXIJ
[13/06/2022 20:33:35] [INFO] Demarcation: 12
[13/06/2022 20:33:35] [CRITICAL] RES_BASE_URI
Traceback (most recent call last):
  File "tv.py", line 1191, in <module>
    config = mtv.get_service_config()
  File "tv.py", line 532, in get_service_config
    'tvChannelLogoPath': '%s%s' % (platform['RES_BASE_URI'], params['tvChannelLogoPath']),
KeyError: 'RES_BASE_URI'
```

Comunicación con los servidores tengo sin problema:

```bash
pi@miniPC:~/git/movistar$ nslookup www-60.svc.imagenio.telefonica.net
Server:         80.58.61.254
Address:        80.58.61.254#53

Non-authoritative answer:
Name:   www-60.svc.imagenio.telefonica.net
Address: 172.26.22.23
```

Y no obtengo ningún error al ejecutar estos comandos para consultar datos:

```bash
wget -nv -O - http://www-60.svc.imagenio.telefonica.net:2001/appserver/mvtv.do?action=getPlatformProfile && \
wget -nv -O - http://www-60.svc.imagenio.telefonica.net:2001/appserver/mvtv.do?action=getClientProfile
```
Un saludo

**Comment by MovistarTV** [comment]
Hola,

El error se debe a que ha cambiado la clave, ahora es `res_BASE_URI` en vez de `RES_BASE_URI`.

Edita el grabber y cámbialo, pero no si será suficiente o habrá más errores. Desde que codificaron los canales no he vuelto a usarlo...

Saludos.

**Comment by Lordpedal** [comment]
Buenas   @MovistarTV ,

Siento no haber dado una respuesta antes, te tengo que decir que eres un crack y **espero que no te desanimes con este proyecto tan grande que has conseguido**.

Solucionado con el cambio propuesto, por si quieres actualizar el repositorio.

Un gran saludo

**Comment by MovistarTV** [comment]
Gracias.

Acabo de actualizar el grabber.

Saludos.
