### ISSUE TITLE
Error generando contenido local - [ SOLUCIONADO ]

### ISSUE THREAD

**Issue by Lordpedal** [MovistarTV/tv_grab_es_movistartv#34]
Buenos días,

Desde ayer estoy recibiendo los siguientes errores:

```bash
pi@overclock:~/git/movistar$ ./tv_grab_es_movistartv.py --reset
pi@overclock:~/git/movistar$ ./tv_grab_es_movistartv.py --m3u Lordpedal.m3u
Excepción:

         dvbipiEntryPoint

Traceback:

        Traceback (most recent call last):
  File "./tv.py", line 1190, in <module>
    config = mtv.get_service_config()
  File "./tv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')
KeyError: 'dvbipiEntryPoint'

pi@overclock:~/git/movistar$ ./tv_grab_es_movistartv.py --output Lordpedal.xml
Excepción:

         dvbipiEntryPoint

Traceback:

        Traceback (most recent call last):
  File "./tv.py", line 1190, in <module>
    config = mtv.get_service_config()
  File "./tv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')
KeyError: 'dvbipiEntryPoint'
```
Y revisando el **log** muestra los siguientes errores:

```bash
pi@overclock:~/git/movistar/xmltv$ cat tv_grab_es_movistartv.log
[30/01/2021 12:06:43] [INFO] ---------------------------------------------------
[30/01/2021 12:06:43] [INFO] MovistarTV EPG Grabber
[30/01/2021 12:06:43] [INFO] Parámetros: ['--m3u', 'Lordpedal.m3u']
[30/01/2021 12:06:43] [INFO] ---------------------------------------------------
[30/01/2021 12:06:43] [INFO] Creando caché en /home/pi/git/movistar/xmltv/cache
[30/01/2021 12:06:43] [INFO] Cookie: no encontrada
[30/01/2021 12:06:43] [INFO] Descargando configuración del cliente
[30/01/2021 12:06:46] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:06:50] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:06:53] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:06:56] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:06:56] [ERROR] End Point http://www-60.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:06:59] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:07:02] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:07:05] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:07:08] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:07:08] [ERROR] End Point http://nc2.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:07:11] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:07:14] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:07:17] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:07:20] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:07:20] [ERROR] End Point http://nc4.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:07:23] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:07:26] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:07:29] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:07:33] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:07:33] [ERROR] End Point http://nc5.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:07:36] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:07:39] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:07:42] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:07:45] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:07:45] [ERROR] End Point http://nc6.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:07:45] [ERROR] Servicio Web de Movistar TV caído: decargando guía básica
[30/01/2021 12:07:45] [ERROR] Usando la configuración de cliente por defecto: 12|ALL|1
[30/01/2021 12:07:45] [INFO] Descargando pefil del servicio
[30/01/2021 12:07:45] [ERROR] Usando el pefil del servicio por defecto
[30/01/2021 12:07:45] [INFO] Descargando parámetros de configuración
[30/01/2021 12:07:45] [ERROR] Usando los parámetros de configuración por defecto
[30/01/2021 12:07:45] [CRITICAL] dvbipiEntryPoint
Traceback (most recent call last):
  File "./tv.py", line 1190, in <module>
    config = mtv.get_service_config()
  File "./tv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')
KeyError: 'dvbipiEntryPoint'

[30/01/2021 12:08:27] [INFO] ---------------------------------------------------
[30/01/2021 12:08:27] [INFO] MovistarTV EPG Grabber
[30/01/2021 12:08:27] [INFO] Parámetros: ['--output', 'Lordpedal.xml']
[30/01/2021 12:08:27] [INFO] ---------------------------------------------------
[30/01/2021 12:08:27] [INFO] Cookie: no encontrada
[30/01/2021 12:08:27] [INFO] Descargando configuración del cliente
[30/01/2021 12:08:30] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:08:33] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:08:36] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:08:40] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:08:40] [ERROR] End Point http://www-60.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:08:43] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:08:46] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:08:49] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:08:52] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:08:52] [ERROR] End Point http://nc2.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:08:55] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:08:58] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:09:01] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:09:04] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:09:04] [ERROR] End Point http://nc4.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:09:07] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:09:10] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:09:13] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:09:16] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:09:16] [ERROR] End Point http://nc5.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:09:19] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 12:09:23] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 12:09:26] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 12:09:29] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 12:09:29] [ERROR] End Point http://nc6.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 12:09:29] [ERROR] Servicio Web de Movistar TV caído: decargando guía básica
[30/01/2021 12:09:29] [ERROR] Usando la configuración de cliente por defecto: 12|ALL|1
[30/01/2021 12:09:29] [INFO] Descargando pefil del servicio
[30/01/2021 12:09:29] [ERROR] Usando el pefil del servicio por defecto
[30/01/2021 12:09:29] [INFO] Descargando parámetros de configuración
[30/01/2021 12:09:29] [ERROR] Usando los parámetros de configuración por defecto
[30/01/2021 12:09:29] [CRITICAL] dvbipiEntryPoint
Traceback (most recent call last):
  File "./tv.py", line 1190, in <module>
    config = mtv.get_service_config()
  File "./tv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')
KeyError: 'dvbipiEntryPoint'
```

Adicionalmente he comprobado respuesta de DNS y me devuelve la siguiente respuesta:

```bash
pi@overclock:~/git/movistar/$ nslookup www-60.svc.imagenio.telefonica.net
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   www-60.svc.imagenio.telefonica.net
Address: 172.26.22.23
```

En el script lo he probado tanto con `use_multithread = False` como `use_multithread = True` y con las **DNS** `80.58.61.254 80.58.61.250` , como `172.26.23.3`

Desconozco si es un fallo puntual de mi sistema o bien han cambiado las direcciones de obtención de EPG

Un saludo y gran trabajo

**Comment by MovistarTV** [comment]
No consigo reproducir el error que te está dando:
```sh
[30/01/2021 13:28:57] [INFO] ---------------------------------------------------
[30/01/2021 13:28:57] [INFO] MovistarTV EPG Grabber
[30/01/2021 13:28:57] [INFO] Parámetros: ['--output', 'guia.xml']
[30/01/2021 13:28:57] [INFO] ---------------------------------------------------
[30/01/2021 13:28:57] [INFO] Cookie: no encontrada
[30/01/2021 13:28:57] [INFO] Descargando configuración del cliente
[30/01/2021 13:28:57] [INFO] Set-Cookie: JSESSIONID=XXXXXXXXXXXXXXXXXXXXXXX-node1; Path=/appserver; HttpOnly
[30/01/2021 13:28:57] [INFO] Descargando pefil del servicio
[30/01/2021 13:28:57] [INFO] Descargando parámetros de configuración
[30/01/2021 13:39:57] [INFO] tvPackages: UTXC3|UTXCP|UTXF9
[30/01/2021 13:39:58] [INFO] Demarcation: 13
[30/01/2021 13:40:03] [INFO] Nuevos End Points: [u'epNoCach8', u'epNoCach9', u'epNoCach4', u'epNoCach5', u'epNoCach6', u'epNoCach7', u'epNoCach1', u'epNoCach2', u'epNoCach3', u'epNoCach10', u'epNoCach11']
[30/01/2021 13:40:03] [INFO] Descargando mapa de géneros
[30/01/2021 13:40:03] [INFO] Buscando el Proveedor de Servicios de Asturias
[30/01/2021 13:40:06] [INFO] Proveedor de Servicios de Asturias: 239.0.2.150
[30/01/2021 13:40:06] [INFO] Descargando canales, paquetes e índices
[30/01/2021 13:40:44] [INFO] Canales: 426
[30/01/2021 13:40:44] [INFO] Paquetes: 398
[30/01/2021 13:40:44] [INFO] Días de EPG: 8
[30/01/2021 13:40:49] [INFO] Multithread: 3 descargas simultáneas
[30/01/2021 13:40:49] [INFO] Descargando EPG_0_BIN.imagenio.es
[30/01/2021 13:40:49] [INFO] Descargando EPG_1_BIN.imagenio.es
[30/01/2021 13:40:49] [INFO] Descargando EPG_2_BIN.imagenio.es
[30/01/2021 13:41:06] [INFO] Descargando EPG_3_BIN.imagenio.es
[30/01/2021 13:42:13] [INFO] Descargando EPG_4_BIN.imagenio.es
[30/01/2021 13:42:14] [INFO] Descargando EPG_5_BIN.imagenio.es
[30/01/2021 13:42:28] [INFO] Descargando EPG_6_BIN.imagenio.es
[30/01/2021 13:43:36] [INFO] Descargando EPG_7_BIN.imagenio.es
[30/01/2021 13:47:13] [INFO] Generando la guía XMLTV: descargando info extendida
[...]
```
Han hecho cambios, pero el grabber sigue funcionando bien, al menos en mi demarcación.

Borra todo el directorio de la caché:
```sh
rm -rf /home/pi/git/movistar/xmltv/cache
```

E inténtalo otra vez...

**Comment by Lordpedal** [comment]
Fue lo primero que hice:

```bash
pi@overclock:~/git/movistar$ ./tv_grab_es_movistartv.py --reset
```

Y daba el error que comentaba, ahora he hecho lo que comentas:

```bash
pi@overclock:~/git/movistar$ rm -rf /home/pi/git/movistar/xmltv/cache
```

Y sigue en el mismo error:

```bash
[30/01/2021 14:06:42] [INFO] ---------------------------------------------------
[30/01/2021 14:06:42] [INFO] MovistarTV EPG Grabber
[30/01/2021 14:06:42] [INFO] Parámetros: ['--m3u', 'lordpedal.m3u']
[30/01/2021 14:06:42] [INFO] ---------------------------------------------------
[30/01/2021 14:06:42] [INFO] Cookie: no encontrada
[30/01/2021 14:06:42] [INFO] Descargando configuración del cliente
[30/01/2021 14:06:45] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 14:06:49] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 14:06:52] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 14:06:55] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 14:06:55] [ERROR] End Point http://www-60.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 14:06:58] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 14:07:01] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 14:07:04] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 14:07:07] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 14:07:07] [ERROR] End Point http://nc2.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 14:07:10] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 14:07:13] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 14:07:16] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 14:07:19] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 14:07:19] [ERROR] End Point http://nc4.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 14:07:22] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 14:07:25] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 14:07:28] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 14:07:32] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 14:07:32] [ERROR] End Point http://nc5.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 14:07:35] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 14:07:38] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 14:07:41] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 14:07:44] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 14:07:44] [ERROR] End Point http://nc6.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 14:07:44] [ERROR] Servicio Web de Movistar TV caído: decargando guía básica
[30/01/2021 14:07:44] [ERROR] Usando la configuración de cliente por defecto: 12|ALL|1
[30/01/2021 14:07:44] [INFO] Descargando pefil del servicio
[30/01/2021 14:07:44] [ERROR] Usando el pefil del servicio por defecto
[30/01/2021 14:07:44] [INFO] Descargando parámetros de configuración
[30/01/2021 14:07:44] [ERROR] Usando los parámetros de configuración por defecto
[30/01/2021 14:07:44] [CRITICAL] dvbipiEntryPoint
Traceback (most recent call last):
  File "./tv.py", line 1190, in <module>
    config = mtv.get_service_config()
  File "./tv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')
KeyError: 'dvbipiEntryPoint'

[30/01/2021 14:16:32] [INFO] ---------------------------------------------------
[30/01/2021 14:16:32] [INFO] MovistarTV EPG Grabber
[30/01/2021 14:16:32] [INFO] Parámetros: ['--output', 'guia.xml']
[30/01/2021 14:16:32] [INFO] ---------------------------------------------------
[30/01/2021 14:16:32] [INFO] Cookie: no encontrada
[30/01/2021 14:16:32] [INFO] Descargando configuración del cliente
[30/01/2021 14:16:35] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 14:16:38] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 14:16:41] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 14:16:45] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 14:16:45] [ERROR] End Point http://www-60.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 14:16:48] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 14:16:51] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 14:16:54] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 14:16:57] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 14:16:57] [ERROR] End Point http://nc2.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 14:17:00] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 14:17:03] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 14:17:06] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 14:17:09] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 14:17:09] [ERROR] End Point http://nc4.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 14:17:12] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 14:17:15] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 14:17:18] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 14:17:21] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 14:17:21] [ERROR] End Point http://nc5.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 14:17:24] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 3
[30/01/2021 14:17:28] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 2
[30/01/2021 14:17:31] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 1
[30/01/2021 14:17:34] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 0
[30/01/2021 14:17:34] [ERROR] End Point http://nc6.svc.imagenio.telefonica.net:2001 desactivado
[30/01/2021 14:17:34] [ERROR] Servicio Web de Movistar TV caído: decargando guía básica
[30/01/2021 14:17:34] [ERROR] Usando la configuración de cliente por defecto: 12|ALL|1
[30/01/2021 14:17:34] [INFO] Descargando pefil del servicio
[30/01/2021 14:17:34] [ERROR] Usando el pefil del servicio por defecto
[30/01/2021 14:17:34] [INFO] Descargando parámetros de configuración
[30/01/2021 14:17:34] [ERROR] Usando los parámetros de configuración por defecto
[30/01/2021 14:17:34] [CRITICAL] dvbipiEntryPoint
Traceback (most recent call last):
  File "./tv.py", line 1190, in <module>
    config = mtv.get_service_config()
  File "./tv.py", line 521, in get_service_config
    dvb_entry_point = platform['dvbConfig']['dvbipiEntryPoint'].split(':')
KeyError: 'dvbipiEntryPoint'
```

La demarcación que yo uso es la **12** y tu estas en la **13** por lo visto, quizas el cambio sea por zona como bien comentas.

**Comment by MovistarTV** [comment]
Intenta acceder con el navegador (o con `curl`, `wget` o similar) aquí:

http://www-60.svc.imagenio.telefonica.net:2001/appserver/mvtv.do?action=getClientProfile

Y aquí:

http://www-60.svc.imagenio.telefonica.net:2001/appserver/mvtv.do?action=getPlatformProfile

Y **no** pegues la respuesta, con saber si ves los datos del servicio de momento es suficiente.

**Comment by Lordpedal** [comment]
Entrar puedo entrar en los enlaces, aunque los Endpoint del Grabber son difierenes.

Acabo de dar con el problema que tenía, mis sospechas eran por Python y la versión de ejecución:

En una maquina **Debian 9**:

```bash
pi@overclock:~/git/movistar$ python -V
Python 2.7.13
```

Y en la otra **Debian 10**:

```bash
pi@overclock:~/git/movistar$ python -V
Python 2.7.16
```

Hasta ahora los generaba en el sistema **`Debian 9`** sin problemas y de repente han caido.

Se ha podido solucionar con un swap de HD y sin problemas sistema a espejo uno del otro tomando de base **`Debian 10`**.

```bash
pi@overclock:~/git/movistar/xmltv$ cat tv_grab_es_movistartv.log
[30/01/2021 15:34:45] [INFO] ---------------------------------------------------
[30/01/2021 15:34:45] [INFO] MovistarTV EPG Grabber
[30/01/2021 15:34:45] [INFO] Parámetros: ['--m3u', 'lordpedal.m3u']
[30/01/2021 15:34:45] [INFO] ---------------------------------------------------
[30/01/2021 15:34:45] [INFO] Creando caché en /home/pi/git/movistar/xmltv/cache
[30/01/2021 15:34:45] [INFO] Cookie: no encontrada
[30/01/2021 15:34:45] [INFO] Descargando configuración del cliente
[30/01/2021 15:34:45] [INFO] Set-Cookie: JSESSIONID=XXXXXXXXXXXXXXXXXXXXXXX-node11; Path=/appserver; HttpOnly
[30/01/2021 15:34:45] [INFO] Descargando pefil del servicio
[30/01/2021 15:34:45] [INFO] Descargando parámetros de configuración
[30/01/2021 15:34:45] [INFO] tvPackages: UTXCP|UTXF1
[30/01/2021 15:34:45] [INFO] Demarcation: 12
[30/01/2021 15:34:45] [INFO] Nuevos End Points: [u'epNoCach8', u'epNoCach9', u'epNoCach4', u'epNoCach5', u'epNoCach6', u'epNoCach7', u'epNoCach1', u'epNoCach2', u'epNoCach3', u'epNoCach10', u'epNoCach11']
[30/01/2021 15:34:45] [INFO] Descargando mapa de géneros
[30/01/2021 15:34:45] [INFO] Buscando el Proveedor de Servicios de Murcia
[30/01/2021 15:34:47] [INFO] Proveedor de Servicios de Murcia: 239.0.2.148
[30/01/2021 15:34:47] [INFO] Descargando canales, paquetes e índices
[30/01/2021 15:35:15] [INFO] Canales: 426
[30/01/2021 15:35:15] [INFO] Paquetes: 398
[30/01/2021 15:35:15] [INFO] Días de EPG: 8
[30/01/2021 15:35:16] [INFO] Lista de canales exportada: lordpedal.m3u
```

Muchas gracias por tu tiempo y esfuerzo, siento las molestias **`_WiLloW_`**

**Comment by MovistarTV** [comment]
No importa, los EndPoint del grabber son sólo para la primera conexión. Se empieza usando `www-60` que es el principal y si está caído lo intenta con los demás, que eran los que estaban activos hace un tiempo.

Si puedes acceder con el navegador desde un PC, tienes un problema en la RPi:
```sh
Timeout: http://www-60.svc.imagenio.telefonica.net:2001
```
Conecta por SSH a la RPi y mira a ver qué pasa si intentas descargar los datos del servicio desde ahí:
```sh
wget -nv -O - http://www-60.svc.imagenio.telefonica.net:2001/appserver/mvtv.do?action=getClientProfile
```
Si no hay errores lo siguiente sería mirar Python.

Y edita el grabber y pon el nivel de registro a `DEBUG`:
```sh
log_level = logging.DEBUG
```

**Comment by MovistarTV** [comment]
Vale, solucionado entonces...

**Comment by Lordpedal** [comment]
> 
> 
> Vale, solucionado entonces...

Lo dicho muchas gracias por mantener este proyecto y siento haber abierto un ticket pero me había bloqueado en los tests previos.

Un saludo
